[tool]
[tool.poetry]
authors = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
description = "[meta]programming [L]anguage"
name = "metaL"
version = "0.0.1"
[tool.poetry.dependencies]
python = "^3.8"
pytest = "^6.0.1"
xxhash = "^1.4.4"
ply = "^3.11"
[tool.poetry.dev-dependencies]
pytest = ""
