
# \ <section:head>

CWD     = $(CURDIR)
MODULE  = $(notdir $(CWD))
OS     ?= $(shell uname -s)

NOW = $(shell date +%d%m%y)
REL = $(shell git rev-parse --short=4 HEAD)

# / <section:head>


# \ <section:demos>


# / <section:demos>



# \ <section:tail>


# / <section:tail>

