
# \ <section:head>

CWD     = $(CURDIR)
MODULE  = $(notdir $(CWD))
OS     ?= $(shell uname -s)

NOW = $(shell date +%d%m%y)
REL = $(shell git rev-parse --short=4 HEAD)

# \ <section:python tools>

PIP = $(CWD)/bin/pip3

# / <section:python tools>



# / <section:head>


# \ <section:django>


# / <section:django>



# \ <section:tail>


# / <section:tail>

